<?php if($block->getSetting('enabled')):?>
    <div
        class="sticky-notification-bar"
        style="background-color: <?php echo $this->getSetting('background_color')?>; color: <?php echo $this->getSetting('text_color')?>;">
        <span class="content"><?php echo $block->getSetting('content')?></span>
    </div>
    <style>
        <?php echo $block->getSetting("custom_css")?>
    </style>
    <?php if ($block->getSetting('is_sticky')):?>
        <script>
            require(["jquery"], function ($) {
                $(".sticky-notification-bar").css('position', 'fixed');
                $(".page-header").css("margin-top", $('.sticky-notification-bar').height()+"px");
            });
        </script>
    <?php endif;?>
<?php endif;?>
