<div class="redchamps-info">
    <h4 style="margin:0;">
        This is a product of RedChamps.
        You can visit our website at -
        <a target="_blank" style="text-decoration:none;" href="https://redchamps.com">
            redChamps.com
        </a>
        or you can become our friend by following us on
        <a target="_blank" style="text-decoration:none;" href="https://twitter.com/redChampsteam">
            Twitter
        </a>
        /
        <a target="_blank" style="text-decoration:none;" href="https://www.facebook.com/redChampsofficial">
            Facebook
        </a>
    </h4>
</div>