<div class="redchamps-info">
    <h4 style="margin:0;">
        This is a product of RedChamps.
        You can visit our
        <a target="_blank" style="text-decoration:none;" href="https://redchamps.com">
            website
        </a>
        or follow us on
        <a target="_blank" style="text-decoration:none;" href="https://twitter.com/_redChamps">
            Twitter
        </a>
        for updates about new extension releases.
    </h4>
</div>
